# you should write an all-in-one Dockerfile for your fuzz target
# it should build the project and any test harnesses with coverage
# instrumentation, and provide a simple script, fuzz.sh, that executes
# your fuzzing commands
FROM cmuqa/fuzzing:base
